server:
  port: 8072

spring:
  application:
    name: gateway-service


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 992601312462-24jl5rl4s2tn0ghtmn368ldfi8pvv3o3.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email, https://www.googleapis.com/auth/cloud-platform
            redirect-uri: "http://localhost:8072/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  cloud:
    gcp:
      project-id: ticketservice-479913
    gateway:
      routes:
        - id: ticket-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/tickets/**
          filters:
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - AddResponseHeader=X-Gateway-Response-Time, ${T(java.time.Instant).now()}
            - name: CustomHeaderFilter

      default-filters:
        - AddRequestHeader=X-Requested-With, Gateway-Service
        - AddResponseHeader=X-Content-Type-Options, nosniff

        - name: CustomRegionFilter
          args:
            region: EU-RO
            contentLanguage: ro-RO
            originRegion: Romania
            contentLocation: Europe/Romania

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
