server:
  port: 8072

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1072236033390-o1cl64d5dsi84gglt9fj9v8d68u4toro.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "http://localhost:8072/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  cloud:
    gateway:
      routes:
        - id: artist-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/artists/**
          filters:
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - AddResponseHeader=X-Gateway-Response-Time, ${T(java.time.Instant).now()}
            - name: CustomHeaderFilter
          stripPrefix: false
      default-filters:
        - AddRequestHeader=X-Requested-With, Gateway-Service
        - AddResponseHeader=X-Content-Type-Options, nosniff
        - name: CustomRegionFilter
          args:
            region: EU-RO
            contentLanguage: ro-RO
            originRegion: Romania
            contentLocation: Europe/Romania

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,shutdown
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted

logging:
  level:
    org:
      example:
        gateway: INFO
    org.springframework.cloud.gateway: DEBUG

