server:
  port: ${SERVER_PORT:8072}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:gateway-service}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 495831365838-5oul8qjj85osu680oi03kufql12ktkr5.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email, https://www.googleapis.com/auth/cloud-platform
            redirect-uri: "http://localhost:8072/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  cloud:
    gcp:
      project-id: escobarteam
    gateway:
      routes:
        # Artist Service Routes
        - id: artist-service
          uri: ${ARTIST_SERVICE_URI:http://artist-service:8080}
          predicates:
            - Path=/api/artists/**
          filters:
            - AddRequestHeader=X-Requested-With, Gateway-Service
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - name: CustomHeaderFilter
          stripPrefix: false
        
        # Event Service Routes
        - id: event-service
          uri: ${EVENT_SERVICE_URI:http://event-service:8081}
          predicates:
            - Path=/api/events/**
          filters:
            - AddRequestHeader=X-Requested-With, Gateway-Service
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - name: CustomHeaderFilter
          stripPrefix: false
        
        # Stage Service Routes
        - id: stage-service
          uri: ${EVENT_SERVICE_URI:http://event-service:8081}
          predicates:
            - Path=/api/stages/**
          filters:
            - AddRequestHeader=X-Requested-With, Gateway-Service
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - name: CustomEventSizeFilter
          stripPrefix: false
        
        # Ticket Service Routes
        - id: ticket-service
          uri: ${TICKET_SERVICE_URI:http://ticket-service:8083}
          predicates:
            - Path=/api/tickets/**
          filters:
            - AddRequestHeader=X-Requested-With, Gateway-Service
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - name: CustomHeaderFilter
          stripPrefix: false
      
      default-filters:
        - AddRequestHeader=X-Requested-With, Gateway-Service
        - AddResponseHeader=X-Content-Type-Options, nosniff
        - name: CustomRegionFilter
          args:
            region: EU-RO
            contentLanguage: ro-RO
            originRegion: Romania
            contentLocation: Europe/Romania

  zipkin:
    base-url: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    preferIpAddress: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://zipkin:9411}/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers,shutdown,gateway
  endpoint:
    health:
      show-details: always
    shutdown:
      access: unrestricted

logging:
  level:
    org:
      example:
        gateway: INFO
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN

google:
  cloud:
    project-id: escobarteam
