server:
  port: 8081

spring:
  application:
    name: gateway-service

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:public.key

  cloud:
    gateway:
      routes:
        - id: ticket-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/tickets/**
          filters:
            - AddRequestHeader=X-Gateway-Request-Id, ${random.uuid}
            - AddResponseHeader=X-Gateway-Response-Time, ${T(java.time.Instant).now()}
            - name: CustomHeaderFilter

      default-filters:
        - AddRequestHeader=X-Requested-With, Gateway-Service
        - AddResponseHeader=X-Content-Type-Options, nosniff

        - name: CustomRegionFilter
          args:
            region: EU-RO
            contentLanguage: ro-RO
            originRegion: Romania
            contentLocation: Europe/Romania

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
